# Generated by Django 4.2.13 on 2025-04-29 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="finished_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
